PAGE_ACCESS_TOKEN = 'EAAcu4It8tqIBANbObnNpqZBfkQn3d0Bzxplzs0qaxsQGaEcDoXqrAZCabkirYCnajfUonsjlEcf1GqyFv58sCAezxSJll68VxRO5OcTzAGZC8FLdsxcpcgPs4aBpOT9jIIfSkJyx1fumyZBtk89Rsa9HmLsiVPZB0Od9LKiqrmQZDZD'
FB_SEND_API_URL = 'https://graph.facebook.com/v2.6/me/messages?access_token=' + PAGE_ACCESS_TOKEN
