# Generated by Django 2.0.5 on 2018-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(blank=True, default='', editable=False, max_length=500)),
                ('manufacturer', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('barcode', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(blank=True, default='', editable=False, max_length=500)),
                ('header', models.TextField(default='')),
                ('receipt', models.ImageField(upload_to='receipts')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan_handler.Product')),
            ],
        ),
    ]
