# Generated by Django 2.0.5 on 2018-05-30 11:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
