# Generated by Django 2.0.5 on 2018-05-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_handler', '0002_auto_20180530_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='header',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='uuid',
        ),
    ]
