# Generated by Django 2.0.5 on 2018-05-30 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan_handler', '0003_auto_20180530_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
