# Generated by Django 2.0.5 on 2018-06-01 23:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan_handler', '0005_auto_20180531_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, default='', max_length=150)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=150), default=[], size=None)),
                ('url', models.URLField(blank=True, default='', max_length=150)),
                ('paragraphs', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=150), default=[], size=None)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan_handler.Product')),
            ],
        ),
    ]
