# Generated by Django 2.0.5 on 2018-06-06 13:34

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan_handler', '0006_receiptnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(blank=True, default='', max_length=150)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=150), default=[], size=None)),
                ('preparation', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=150), default=[], size=None)),
                ('others', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, default='', max_length=150), default=[], size=None)),
                ('recipe_url', models.URLField(blank=True, default='', max_length=150)),
                ('recipe_image_url', models.URLField(blank=True, default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan_handler.Product')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scan_handler.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='receiptnew',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReceiptNew',
        ),
    ]
